name: GitHub Actions

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose up --build
            docker-compose ps
